###该类属性： 品牌名id、品牌名、子类商品（非必填）
###是否被删除（默认未删除）、是否展示在客户端（默认不展示）、创建时间、修改时间
###POST增PUT改GET查Delete删（删改可批量）

###新增分类Brand 
POST  http://localhost:8080/mt/brand/addBrand HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "name": "华为77"
}


###修改分类Brand
PUT  http://localhost:8080/mt/brand/editBrand HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "brand_id": "db2b6fa1-5c03-49b9-a5c5-a0c20811e339",
  "name": "华为2",
  "showOut":"UnShow"
}

###批量修改分类Brand是否展示在客户端
PUT  http://localhost:8080/mt/brand/showOutAll HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "showOut":"Show",
  "brand_ids":[
    "db2b6fa1-5c03-49b9-a5c5-a0c20811e338",
    "bb5eb671-a7f5-41f9-9bc1-345e08339988"
  ] 
}

###根据条件分页查找Brand
GET http://localhost:8080/mt/brand/getBrandPage HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "brandDto":{
    "showOut":"Show"
  },
  "myPagaRequest":{
    "page":1,
    "limit":2,
    "sort":"name",
    "dir":"DESC"
  }
}
