###条件分页查找分类Category
GET http://localhost:8080/mt/category/findAllCategories HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "categoryDto":{
    "category_id": "",
    "name": "",
    "showOut": "UnShow"
  },
  "myPagaRequest":{
    "page":1,
    "limit":10,
    "sort":"name",
    "dir":"DESC"
  }
}

###条件分页查找分类Category
GET http://localhost:8080/mt/category/findAllCategories HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "categoryDto":{
    "name": "杜敬威",
    "showOut": "Show"
  },
  "myPagaRequest":{
    "page":1,
    "limit":10,
    "sort":"name",
    "dir":"DESC"
  }
}


###新增分类Category
POST  http://localhost:8080/mt/category/saveCategory HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "category_id": "bb5eb671-a7f5-41f9-9bc1-345e08339988",
  "name": "杜敬威",
  "usable": "UnDeleted",
  "showOut": "UnShow"
}

###批量删除Category
DELETE http://localhost:8080/mt/category/deleteCategories HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "category_ids": [
    "bb5eb671-a7f5-41f9-9bc1-345e08339988",
    "bb5eb671-a7f5-41f9-9bc1-345e08339999"
  ]
}

###单条记录修改分类Category
PUT http://localhost:8080/mt/category/editCategory HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "category_id": "bb5eb671-a7f5-41f9-9bc1-345e08339999",
  "name": "杜敬威1",
  "showOut": "UnShow"
}

###批量操作分类是否显示Category
PUT http://localhost:8080/mt/category/showCategories HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "showOut":"Show",
  "category_ids": [
    "bb5eb671-a7f5-41f9-9bc1-345e08339988",
    "bb5eb671-a7f5-41f9-9bc1-345e08339999"
    ]
}