### 新增管理员
POST  http://localhost:8080/mt/manage/addManage HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "name": "",
  "password":"123"
}

### 新增超级管理员
POST  http://localhost:8080/mt/manage/addManageAdmin HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "name": "admin",
  "password":"123",
  "key":"DJDU"
}

### 登陆
POST  http://localhost:8080/mt/manage/login HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "name": "admin",
  "password":"123"
}


### 条件分页查询
POST http://localhost:8080/mt/manage/findAllManage HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
  "manageDto":{},
  "myPagaRequest":{
    "page":1,
    "limit":8,
    "sort":"creatTime",
    "dir":"DESC"
  }
}

### 删除管理员
POST  http://localhost:8080/mt/manage/delete HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
   "manage_id": "476bc326-3666-4a99-92bc-1657a4dc3a84"
}

### 冻结管理员
POST  http://localhost:8080/mt/manage/state HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
   "manage_id": "476bc326-3666-4a99-92bc-1657a4dc3a84"
}


